server {
    listen 18762;
    server_name _;
    access_log off;

    location = /eew-icon.png {
        alias /srv/eew-icon.png;
        add_header Cache-Control "public, max-age=2592000, immutable";
    }

    location / {
        proxy_pass http://bark-core:18762;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
